services:
  node:
    profiles: ["node"]
    image: node:22
    container_name: node_server
    working_dir: /usr/src/app
    volumes:
      - ./nodejs:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URL=${MONGO_URL}
    ports:
      - "${NODE_PORT}:3000"

  php:
    profiles: ["php"]
    build:
      context: .
      dockerfile: php.Dockerfile
    container_name: php_server
    volumes:
      - ./php:/var/www/html
    ports:
      - "${PHP_PORT}:80"

  nginx:
    profiles: ["nginx"]
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node
      - php

  mysql:
    profiles: ["mysql"]
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    profiles: ["mongo"]
    image: mongo:7
    container_name: mongo_db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  phpmyadmin:
    profiles: ["mysql-tools"]
    image: phpmyadmin:latest
    container_name: phpmyadmin_ui
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"

  adminer:
    profiles: ["admirer-tools"]
    image: adminer:latest
    container_name: adminer_ui
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - "${ADMINER_PORT}:8080"

  mongo-express:
    profiles: ["mongo-tools"]
    image: mongo-express:latest
    container_name: mongo_ui
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: "false"
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"

volumes:
  mysql_data:
  mongo_data:
